Better checks for deps

diff --git a/installer b/installer
--- a/installer
+++ b/installer
@@ -2,12 +2,20 @@
 
 ### Helpers begin
 check_deps() {
+    local missing
     for d in "${deps[@]}"; do
-        [[ -n $(command -v "$d") ]] || errx 128 "$d is not installed"
+        if [[ -z $(command -v "$d") ]]; then
+            # Force absolute path
+            if [[ ! -f "/$d" ]]; then
+                err "$d was not found"
+                missing="true"
+            fi
+        fi
     done; unset d
+    [[ -z $missing ]] || exit 128
 }
 err() { echo -e "${color:+\e[31m}[!] $*\e[0m"; }
-errx() { echo -e "${color:+\e[31m}[!] ${*:2}\e[0m"; exit "$1"; }
+errx() { err "${*:2}"; exit "$1"; }
 good() { echo -e "${color:+\e[32m}[+] $*\e[0m"; }
 info() { echo -e "${color:+\e[37m}[*] $*\e[0m"; }
 long_opt() {
@@ -32,7 +40,7 @@ Install or uninstall vpn script
 Options:
     -d, --dir=INSTALL_DIR    Install to specified directory
     -h, --help               Display this help message
-    --nocolor                Disable colorized output
+    --no-color               Disable colorized output
     -u, --uninstall          Uninstall
 
 EOF
@@ -55,7 +63,7 @@ while [[ $# -gt 0 ]]; do
         "--") shift && args+=("$@") && break ;;
         "-d"|"--dir"*) install_dir="$(long_opt "$@")" || shift ;;
         "-h"|"--help") help="true" ;;
-        "--nocolor") unset color ;;
+        "--no-color") unset color ;;
         "-u"|"--uninstall") action="uninstall" ;;
         *) args+=("$1") ;;
     esac
diff --git a/vpn b/vpn
--- a/vpn
+++ b/vpn
@@ -2,12 +2,20 @@
 
 ### Helpers begin
 check_deps() {
+    local missing
     for d in "${deps[@]}"; do
-        [[ -n $(command -v "$d") ]] || errx 128 "$d is not installed"
+        if [[ -z $(command -v "$d") ]]; then
+            # Force absolute path
+            if [[ ! -f "/$d" ]]; then
+                err "$d was not found"
+                missing="true"
+            fi
+        fi
     done; unset d
+    [[ -z $missing ]] || exit 128
 }
 err() { echo -e "${color:+\e[31m}[!] $*\e[0m"; }
-errx() { echo -e "${color:+\e[31m}[!] ${*:2}\e[0m"; exit "$1"; }
+errx() { err "${*:2}"; exit "$1"; }
 good() { echo -e "${color:+\e[32m}[+] $*\e[0m"; }
 info() { echo -e "${color:+\e[37m}[*] $*\e[0m"; }
 long_opt() {
@@ -52,7 +60,7 @@ Actions:
 Options:
     -g, --gw=GW      Use the specified gateway
     -h, --help       Display this help message
-    --nocolor        Disable colorized output
+    --no-color       Disable colorized output
     -r, --random     Use random VPN gateway
     -v, --vpn=VPN    Use the specified VPN (default: $(default_vpn))
 
@@ -66,6 +74,7 @@ color="true"
 confdir="$HOME/.config/vpn"
 [[ ! -f "$confdir/vpn.conf" ]] || conf="$confdir/vpn.conf"
 deps+=("jq")
+deps+=("openvpn")
 
 # Check for missing dependencies
 check_deps
@@ -76,7 +85,7 @@ while [[ $# -gt 0 ]]; do
         "--") shift && args+=("$@") && break ;;
         "-g"|"--gw"*) gw="$(long_opt "$@")" || shift ;;
         "-h"|"--help") help="true" ;;
-        "--nocolor") clr="--nocolor"; unset color ;;
+        "--no-color") clr="--nocolor"; unset color ;;
         "-r"|"--random") rand="--random" ;;
         "-v"|"--vpn"*) vpn="$(long_opt "$@")" || shift ;;
         *) args+=("$1") ;;
